# Generated by Django 3.0.4 on 2020-06-02 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20200602_0305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='uuid',
        ),
    ]
