# Generated by Django 3.0.4 on 2020-06-02 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20200602_0317'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='imgUrl',
            new_name='avatar',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='desc',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='url',
            new_name='website',
        ),
    ]
